<?php

declare(strict_types=1);
/**
 * This file is part of richard8768/hyperf-passport.
 *
 * @link     https://github.com/richard8768/hyperf-passport
 * @contact  444626008@qq.com
 * @license  https://github.com/richard8768/hyperf-passport/blob/master/LICENSE
 */

namespace Richard\HyperfPassport\Bridge;

use League\OAuth2\Server\Entities\ClientEntityInterface;
use League\OAuth2\Server\Repositories\ClientRepositoryInterface;
use Richard\HyperfPassport\ClientRepository as ClientModelRepository;
use Richard\HyperfPassport\Passport;

class ClientRepository implements ClientRepositoryInterface
{
    /**
     * The client model repository.
     */
    protected ClientModelRepository $clients;

    /**
     * Create a new repository instance.
     */
    public function __construct(ClientModelRepository $clients)
    {
        $this->clients = $clients;
    }

    public function getClientEntity($clientIdentifier): null|Client|ClientEntityInterface
    {
        $record = $this->clients->findActive($clientIdentifier);

        if (! $record) {
            return null;
        }

        return new Client(
            $clientIdentifier,
            $record->name,
            $record->redirect,
            $record->confidential(),
            $record->provider
        );
    }

    public function validateClient($clientIdentifier, $clientSecret, $grantType): bool
    {
        // First, we will verify that the client exists and is authorized to create personal
        // access tokens. Generally personal access tokens are only generated by the user
        // from the main interface. We'll only let certain clients generate the tokens.
        $record = $this->clients->findActive($clientIdentifier);

        if (! $record || ! $this->handlesGrant($record, $grantType)) {
            return false;
        }

        return ! $record->confidential() || $this->verifySecret((string) $clientSecret, $record->secret);
    }

    /**
     * Determine if the given client can handle the given grant type.
     *
     * @param \Richard\HyperfPassport\Client $record
     * @param string $grantType
     */
    protected function handlesGrant($record, $grantType): bool
    {
        if (is_array($record->grant_types) && ! in_array($grantType, $record->grant_types)) {
            return false;
        }

        switch ($grantType) {
            case 'authorization_code':
                return ! $record->firstParty();
            case 'personal_access':
                return $record->personal_access_client && $record->confidential();
            case 'password':
                return $record->password_client;
            case 'client_credentials':
                return $record->confidential();
            default:
                return true;
        }
    }

    /**
     * Verify the client secret is valid.
     *
     * @param string $clientSecret
     * @param string $storedHash
     */
    protected function verifySecret($clientSecret, $storedHash): bool
    {
        $passport = \Hyperf\Support\make(Passport::class);
        return $passport->hashesClientSecrets ? password_verify($clientSecret, $storedHash) : hash_equals($storedHash, $clientSecret);
    }
}
